version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"  # Jenkins UI port
      - "50000:50000"  # Jenkins agent port
    environment:
      DOCKER_HOST: tcp://dind:2375  # Use the dind service to run Docker commands
    depends_on:
      - dind
    volumes:
      - jenkins_home:/var/jenkins_home  # Jenkins data volume
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for Docker in Docker

  dind:
    image: docker:24-dind  # Docker-in-Docker service
    command: --host=tcp://0.0.0.0:2375 --storage-driver=overlay2  # Allows Jenkins to access Docker
    privileged: true  # Docker-in-Docker requires privileged access
    environment:
      DOCKER_TLS_CERTDIR: ""  # Disable TLS certificate verification
    expose:
      - "2375"  # Expose the Docker-in-Docker port

  blueocean:
    image: jenkinsci/blueocean  # Blue Ocean for Jenkins
    ports:
      - "8081:8080"  # Blue Ocean UI port
    depends_on:
      - jenkins
    environment:
      JENKINS_URL: http://jenkins:8080  # Blue Ocean connects to Jenkins
    volumes:
      - jenkins_home:/var/jenkins_home  # Share Jenkins data volume with Blue Ocean

volumes:
  jenkins_home:
    driver: local
